{{- if not .Values.kafka.mTLS.useExistingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.kafka.mTLS.secretName }}
data:
  client.crt: >-
    {{ required "A valid .Values.kafka.mTLS.clientPublicKey entry required!" .Values.kafka.mTLS.clientPublicKey | b64enc | quote }}
  client.key: >-
    {{ required "A valid .Values.kafka.mTLS.clientPrivateKey entry required!" .Values.kafka.mTLS.clientPrivateKey | b64enc | quote }}
  {{- if .Values.kafka.mTLS.isToSetCA }}
  root.crt: >-
    {{ required "A valid .Values.kafka.mTLS.caCertificate entry required!" .Values.kafka.mTLS.caCertificate | b64enc | quote }}
  {{- end }}
type: Opaque
{{- end }}