apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkZXYuY3JpdGljYWxtYW51ZmFjdHVyaW5nLmlvIjp7InVzZXJuYW1lIjoiY21mIiwicGFzc3dvcmQiOiJxYXoxMjNXU1giLCJhdXRoIjoiWTIxbU9uRmhlakV5TTFkVFdBPT0ifX19
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dev.criticalmanufacturing.io-cred
    app.kubernetes.io/instance: dev.criticalmanufacturing.io-cred
   # app.kubernetes.io/version: 10.2.4
    app.kubernetes.io/managed-by: devopscenter.criticalmanufacturing
    devopscenter.criticalmanufacturing/version: "1"
  name: dev.criticalmanufacturing.io-cred
  namespace: nodetest
type: kubernetes.io/dockerconfigjson