apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodetest
  labels:
    app: nodetest
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /etc/data

