apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodetest
  namespace: nodetest
  labels:
    app: nodetest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
