apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmos-pvc
  namespace: cmos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: topolvm-provisioner