kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "clickhouse.name" . }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: {{ .Values.service.nativetls.name }}
