{{- if not .Values.kafka.clientCredentials.useExistingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.kafka.clientCredentials.secretName }}
data:
  client.crt: >-
    {{ required "A valid .Values.kafka.clientCredentials.clientCertificate entry required!" .Values.kafka.clientCredentials.clientPublicKey | b64enc | quote }}
  client.key: >-
    {{ required "A valid .Values.kafka.clientCredentials.clientKey entry required!" .Values.kafka.clientCredentials.clientPrivateKey | b64enc | quote }}
  root.crt: >-
    {{ required "A valid .Values.kafka.clientCredentials.rootCertificate entry required!" .Values.kafka.clientCredentials.caCertificate | b64enc | quote }}
type: Opaque
{{- end }}